apiVersion: v1
kind: Secret
metadata:
  name: tradealpha-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://tradealpha:password@postgres:5432/tradealpha?schema=public&connection_limit=100"
  JWT_SECRET: "tradealpha_secret_key_123_test_only"
